FROM ruby:2.7.1
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update && apt-get install -y \
    build-essential \
    nodejs
RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - && \
    echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list && \
    apt-get update && apt-get install -y --no-install-recommends yarn
WORKDIR /myFirstPortfolio
COPY Gemfile /myFirstPortfolio/Gemfile
COPY Gemfile.lock /myFirstPortfolio/Gemfile.lock
RUN bundle install
COPY . /myFirstPortfolio