version: 2.1
jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.1-node-browsers
    steps:
      - checkout
      # 2回目以降高速に行うため、キャッシュに保存したものを取り出す。ただ、Gemfileを変更した際に前回使用したものでは生じるかもなので、
      # ファイル名・ファイルの中身に応じてハッシュ値を算出する、 checksum 構文を利用している。
      - restore_cache:
          key: Sample_Cache_{{ checksum "Gemfile.lock" }}
      # 初回・Gemfile変更時にはこのコマンドを使用して環境を整える。
      - run:
          name: install Gemfile
          command: bundle install --path vendor/bundle
      # 上記のコマンド結果をキャッシュに保存する。ちなみに、キャッシュ名が既存のものと同じ場合は、実行されない。
      - save_cache:
          key: Sample_Cache_{{ checksum "Gemfile.lock" }}
          paths:
            - ./vendor/bundle
  test:
    docker:
      - image: circleci/ruby:2.7.1-node-browsers
        environment:
          DB_HOST: 127.0.0.1
          DB_PASSWORD: root
      - image: circleci/mysql:5.7
        environment:
          MYSQL_USER: root
          MYSQL_ROOT_PASSWORD: root
    steps:
      - checkout
      - restore_cache:
          key: Sample_Cache_{{ checksum "Gemfile.lock" }}
      # このコマンドを実行しないと、"Your Yarn packages are out of date! Please ... " というエラーが出るので実行
      - run:
          name: if do not execute this, an error occurs.
          command: yarn install --check-files
      # DBの立ち上げを待つ。120秒経っても起動しない場合は、test ジョブを強制終了させる。
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://127.0.0.1:3306 -timeout 120s
      # bundlerの path設定を vendor/bundle にする
      - run:
          name: setup bundler target path
          command: bundle config --local path vendor/bundle
      - run:
          name: Set up DB
          command: |
            bundle exec rake db:create
            bundle exec rails db:migrate
      - run:
          name: implement test
          command: bundle exec rspec ./spec/
  deploy:
    docker:
      - image: circleci/ruby:2.7.1-node-browsers
    steps:
      - checkout
      - restore_cache:
          key: Sample_Cache_{{ checksum "Gemfile.lock" }}
      - run:
          name: deploy app by capistrano
          command: bundle exec cap production deploy
workflows:
  version: 2.1
  test-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master