version: 2.1
jobs:
  build:
    docker:
      # - image: circleci/ruby:2.7.1
      - image: circleci/ruby:2.7.1-node-browsers
    steps:
      - checkout
      - run:
          name: install Gemfile
          command: bundle install
      - save_cache:
          key: SampleMedia_Cache
          paths:
            - Gemfile
            - Gemfile.lock
  test:
    docker:
      - image: circleci/ruby:2.7.1
        environment:
          DB_HOST: 127.0.0.1
          DB_PASSWORD: root
    working_directory: ~/MyMediaApp
    steps:
      - checkout
      - restore_cache:
          key: SampleMedia_Cache
      # - run:
      #     name: Wait for DB
      #     command: dockerize -wait tcp://127.0.0.1:3306 -timeout 120s
      - run:
          name: Set up DB
          command: bundle exec rails db:migrate
      - run:
          name: implement test
          command: bundle exec rspec ./spec/
  deploy:
    docker:
      - image: circleci/ruby:2.7.1
    steps:
      - checkout
      - restore_cache:
          key: SampleMedia_Cache
      - run:
          name: deploy app by capistrano
          command: bundle exec cap production deploy
workflows:
  version: 2.1
  test-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master