version: 2.1
orbs:
  ruby: circleci/ruby@1.1.2
jobs:
  test:
    executor: ruby/default
    steps:
      - checkout
      - ruby/install-deps
      - ruby/rspec-test
      # - ruby/rubocop-check
  deploy:
    executor: ruby/default
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: deploy by capistrano
          command: bundle exec cap production deploy
workflows:
  version: 2.1
  test-deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master