version: 2.1
executors:
  ruby-executor:
    docker:
      - image: circleci/ruby:2.7.1
jobs:
  test:
    executor: ruby-executor
    steps:
      - checkout
      - run:
          name: install Gemfile
          command: bundle update && bundle install
      - run:
          name: sample-test
          command: bundle exec rspec ./spec/
  deploy:
    executor: ruby-executor
    steps:
      - checkout
      - run:
          name: install Gemfile
          command: bundle update && bundle install
      - run:
          name: deploy by capistrano
          command: bundle exec cap production deploy
workflows:
  version: 2.1
  test-deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master