version: 2.1
# orbs:
#   ruby: circleci/ruby@1.1.2
jobs:
  test:
    # executor: ruby/default
    docker:
      - image: circleci/ruby:2.7.1
    steps:
      - checkout
      # - ruby/install-deps
      - run:
          name: install Gemfile
          command: bundle update && bundle install
      - run:
          name: sample-test
          command: bundle exec rspec ./spec/
      # - ruby/rspec-test
      # - ruby/rubocop-check
  deploy:
    # executor: ruby/default
    docker:
      - image: circleci/ruby:2.7.1
    steps:
      - checkout
      # - ruby/install-deps
      # - run:
      #     name: install Gemfile
      #     command: bundle update && bundle install
      - run:
          name: deploy by capistrano
          command: bundle exec cap production deploy
workflows:
  version: 2.1
  test-deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master